In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('customer.csv')

In [ ]:
df.sample(5)

    age  gender   review education purchased
3    72  Female     Good        PG        No
32   92    Male  Average        UG       Yes
28   48    Male     Poor    School        No
45   61    Male     Poor        PG       Yes
9    74    Male     Good        UG       Yes

In [ ]:
df = df.iloc[:,2:]

In [ ]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
from sklearn.model_selection import train_test_split

X = df.iloc[:, :-1] # Features: review, education
y = df.iloc[:, -1]  # Target: purchased

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train

    age  gender   review education
12   51    Male     Poor    School
4    16  Female  Average        UG
37   94    Male  Average        PG
8    65  Female  Average        UG
3    72  Female     Good        PG
6    18    Male     Good    School
41   23    Male     Good        PG
46   64  Female     Poor        PG
47   38  Female     Good        PG
15   75    Male     Poor        UG
9    74    Male     Good        UG
16   59    Male     Poor        UG
24   16  Female  Average        PG
34   86    Male  Average    School
31   22  Female     Poor    School
0    30  Female  Average    School
44   77  Female  Average        UG
27   69  Female     Poor        PG
33   89  Female     Good        PG
5    31  Female  Average    School
29   83  Female  Average        UG
11   74    Male     Good        UG
36   34  Female     Good        UG
1    68  Female     Poor        UG
21   32    Male  Average        PG
2    70  Female     Good        PG
43   27    Male     Poor        PG
35   74    Male     Poor    School
23   96  Female     Good    School
40   39    Male     Good    School
10   98  Female     Good        UG
22   18  Female     Poor        PG
18   19    Male     Good    School
49   25  Female     Good        UG
20   57  Female  Average    School
7    60  Female     Poor    School
42   30  Female     Good        PG
14   15    Male     Poor        PG
28   48    Male     Poor    School
38   45  Female     Good    School

In [ ]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [ ]:
oe.fit(X_train[['review','education']])

ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,).